### ISSUE TITLE
Status sections should show only directories that have relevant files

### ISSUE THREAD

**Issue by joaquimrcarvalho** [time-link/timelink-vscode#1]
In the extension panel the various status sections (Translation Needed, With Errors, With Warnings, etc...) should only show directories when they contain files that have the corresponding status. As it is one has to open every directory to check if there are files inside with the expected status.

**Comment by hobbsi** [comment]
This is going to be more difficult than I initially thought, due to how files/directories and kleio server statuses are being loaded.
