### ISSUE TITLE
Extension cannot connect to kleio-server on windows-home

### ISSUE THREAD

**Issue by joaquimrcarvalho** [time-link/timelink-vscode#4]
On windows Home the kleio server runs inside a virtual machine in a different IP.

The extension gets the kleio server url from mhk-home/system/conf/mhk_system.properties

But the value there should be the url of the kleio container inside the Docker network, something like http://kleio:8088.   

In MacOS if the url is http://host.docker.internal:8088 it works both internally to the Docker Network and in the host machine where the extension runs.

But otherwise the extension needs the external URL of the kleio server and not the one in mhk_system.properties.

Two ways to get it:
1. executing `mhk version` or directly `mhk-home/app/manager `and getting the line "Kleio URL" 

> jrc$ mhk version
> Manager version:  MHK manager version 2019.A1 build 1617 07/05/2020 10:39 
> Docker version:   Docker version 19.03.8, build afacb8b
> Host OS:          mac
> User home:        /Users/jrc
> mhk-home:         /Users/jrc/mhk-home
> mhk-home init:    Sáb 26 Out 2019 10:38:14 WEST
> mhk-home update:  Thu May  7 09:39:47 UTC 2020
> MHK URL:          http://127.0.0.1:8080
> Kleio URL:        http://127.0.0.1:8088
> Portainer URL:    http://127.0.0.1:9000
> type mhk --help for more information

2. From build 1617 onwards the mhk manager stores the external url of the various services in the file `~/.mhk` at each run:

> jrc$ cat ~/.mhk
>HOST_MHK_USER_HOME="/Users/jrc"
>HOST_MHK_HOME="/Users/jrc/mhk-home"
>mhk_home_dir="/Users/jrc/mhki-home"
>MYSQL_OPTS=
>kleio_url=http://127.0.0.1:8088
>mhk_url=http://127.0.0.1:8080
>portainer_url=http://127.0.0.1:9000

**Comment by hobbsi** [comment]
Fixed in release 1.0.3
